
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrum.a2;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Parent;
import java.net.URL;
import javafx.scene.Scene;
import javafx.fxml.FXMLLoader;
import javafx.scene.text.Font;
import java.io.IOException;

public class VendingMachineMain extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception{
        
        
        Font myFont = Font.loadFont(getClass().getResourceAsStream("../../../../resources/main/css/Inika-Bold.ttf"), 20);
        Font myFont2 = Font.loadFont(getClass().getResourceAsStream("../../../../resources/main/font/Modak-Regular.ttf"), 20);
        
        Window window = new Window(new VendingMachine(), primaryStage);

        

    }

}
